// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function EvaluateTransmission(arg1:string):Promise<main.DecisionReportDTO>;

export function GetAgentState():Promise<main.AgentStateDTO>;

export function GetDecisionAudit():Promise<Array<main.AuditRecordDTO>>;

export function GetPacketTimeline():Promise<Array<main.PacketTimelineEntryDTO>>;

export function ParseTransmissionRequest(arg1:string):Promise<main.ParsedTransmissionRequestDTO>;

export function ResetAgentHistory():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
