// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EvaluateTransmission(arg1) {
  return window['go']['main']['AgentApp']['EvaluateTransmission'](arg1);
}

export function GetAgentState() {
  return window['go']['main']['AgentApp']['GetAgentState']();
}

export function GetDecisionAudit() {
  return window['go']['main']['AgentApp']['GetDecisionAudit']();
}

export function GetPacketTimeline() {
  return window['go']['main']['AgentApp']['GetPacketTimeline']();
}

export function ParseTransmissionRequest(arg1) {
  return window['go']['main']['AgentApp']['ParseTransmissionRequest'](arg1);
}

export function ResetAgentHistory() {
  return window['go']['main']['AgentApp']['ResetAgentHistory']();
}

export function Startup(arg1) {
  return window['go']['main']['AgentApp']['Startup'](arg1);
}
