// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {protocol} from '../models';
import {domain} from '../models';

export function DisableLink(arg1:string,arg2:string):Promise<void>;

export function DisableNode(arg1:string):Promise<void>;

export function DisableTower(arg1:string,arg2:number):Promise<void>;

export function EnableLink(arg1:string,arg2:string):Promise<void>;

export function EnableNode(arg1:string):Promise<void>;

export function EnableTower(arg1:string,arg2:number):Promise<void>;

export function GetUniverse():Promise<protocol.UniverseResponse>;

export function ResetNetwork():Promise<void>;

export function StartTransmission(arg1:protocol.TransmissionRequest):Promise<domain.TransmissionResult>;
