// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisableLink(arg1, arg2) {
  return window['go']['main']['App']['DisableLink'](arg1, arg2);
}

export function DisableNode(arg1) {
  return window['go']['main']['App']['DisableNode'](arg1);
}

export function DisableTower(arg1, arg2) {
  return window['go']['main']['App']['DisableTower'](arg1, arg2);
}

export function EnableLink(arg1, arg2) {
  return window['go']['main']['App']['EnableLink'](arg1, arg2);
}

export function EnableNode(arg1) {
  return window['go']['main']['App']['EnableNode'](arg1);
}

export function EnableTower(arg1, arg2) {
  return window['go']['main']['App']['EnableTower'](arg1, arg2);
}

export function GetUniverse() {
  return window['go']['main']['App']['GetUniverse']();
}

export function ResetNetwork() {
  return window['go']['main']['App']['ResetNetwork']();
}

export function StartTransmission(arg1) {
  return window['go']['main']['App']['StartTransmission'](arg1);
}
